name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: .NET Build
      run: dotnet build --no-restore
    - name: .NET Test
      run: dotnet test --no-build --verbosity normal
    - name: Container test
      shell: pwsh
      run: |
        cd wcjvm
        .\Build.ps1
    - name: .NET Publish
      run: dotnet publish --configuration Release --output ./publish
    - name: Upload artifact for release job
      uses: actions/upload-artifact@v3
      with:
        name: wcjvm
        path: ./wcjvm/out/net7.0/win-x64/wcjvm.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "./wcjvm/out/net7.0/win-x64/wcjvm.exe"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}